name: AWS SSM Send-Command Example

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
					aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
					aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
					aws-region: ap-south-1a
					instance-ids: ${{ secrets.INSTANCE_ID  }}
					comment: Deploy the master branch
					working-directory: /home/ubuntu/MERN-Ecommerce
					command: /bin/sh ./deploy.sh